#!/bin/bash

# add grpc_cli
export PATH="${PATH}:/Users/andrew.gunsch/src/grpc/cmake/build"

if ! which node > /dev/null; then
    nvm use 22
fi
alias mydevvit=/Users/andrew.gunsch/src/devvit/packages/cli/bin/devvit.js

source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
source $(brew --prefix)/opt/chruby/share/chruby/auto.sh

# Destroy the monorepo and rebuild
alias nuke="yarn cache clean --all && git clean -dffx && yarn && yarn build --force"

